### ISSUE TITLE
At start

### ISSUE THREAD

**Issue by w495** [bem/project-stub#27] opened 2013-10-08 09:57 UTC
HTTP error 500

    Error: Cannot find module 'esprima'
        at Function.Module._resolveFilename (module.js:338:15)
        at Function.Module._load (module.js:280:25)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at Object. (/home/w495/work/projects/yandex/yabs/bem/stub/project-stub/libs/bem-core/node_modules/bemhtml-compat/lib/compat.js:2:15)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at Object. (/home/w495/work/projects/yandex/yabs/bem/stub/project-stub/libs/bem-core/.bem/techs/bemhtml.js:4:14)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at exports.getTechClass (/home/w495/work/projects/yandex/yabs/bem/stub/project-stub/node_modules/bem/lib/tech/index.js:18:48)
        at exports.createTech (/home/w495/work/projects/yandex/yabs/bem/stub/project-stub/node_modules/bem/lib/tech/index.js:58:21)
        at exports.Level.INHERIT.createTech (/home/w495/work/projects/yandex/yabs/bem/stub/project-stub/node_modules/bem/lib/level.js:154:16)
        at exports.Level.INHERIT.getTech (/home/w495/work/projects/yandex/yabs/bem/stub/project-stub/node_modules/bem/lib/level.js:141:43)
        at registry.decl.__constructor (/home/w495/work/projects/yandex/yabs/bem/stub/project-stub/node_modules/bem/lib/nodes/build.js:51:39)
        at res.(anonymous function) [as __constructor] (/home/w495/work/projects/yandex/yabs/bem/stub/project-stub/node_modules/bem/node_modules/inherit/lib/inherit.js:28:32)
        at res [as __self] (/home/w495/work/projects/yandex/yabs/bem/stub/project-stub/node_modules/bem/node_modules/inherit/lib/inherit.js:48:43)
        at registry.decl.setBemBuildNode (/home/w495/work/projects/yandex/yabs/bem/stub/project-stub/node_modules/bem/lib/nodes/bundle.js:195:25)
        at registry.decl.createDefaultTechNode (/home/w495/work/projects/yandex/yabs/bem/stub/project-stub/node_modules/bem/lib/nodes/bundle.js:320:21)
        at registry.decl.createTechNode (/home/w495/work/projects/yandex/yabs/bem/stub/project-stub/node_modules/bem/lib/nodes/bundle.js:84:24)
        at null. (/home/w495/work/projects/yandex/yabs/bem/stub/project-stub/node_modules/bem/lib/nodes/bundle.js:62:37)
        at Array.map (native)
        at null. (/home/w495/work/projects/yandex/yabs/bem/stub/project-stub/node_modules/bem/lib/nodes/bundle.js:61:29)
        at makePromise.apply (/home/w495/work/projects/yandex/yabs/bem/stub/project-stub/node_modules/bem/node_modules/q/q.js:927:26)
        at makePromise.promise.promiseDispatch (/home/w495/work/projects/yandex/yabs/bem/stub/project-stub/node_modules/bem/node_modules/q/q.js:634:41)
        at Object._onImmediate (/home/w495/work/projects/yandex/yabs/bem/stub/project-stub/node_modules/bem/node_modules/q/q.js:1245:25)
        at processImmediate [as _immediateCallback] (timers.js:330:15)

It can be fixed with `npm install  esprima`

**Comment by kaleb** [comment] 2015-01-09 18:47
bem make is not on the readme, but when I ran it, I got this error:

> Error: Tech module with path '/home/kaleb.hornsby/src/gh/bem/project-stub/libs/bem-core/libs/bem-core/.bem/techs/browser.js.js' not found on require search paths

**Comment by zxqfox** [comment] 2015-01-09 18:51
@kaleb Maker can't find a `tech` (code that know how to work with `browser.js` files in blocks) so It's more like configuration trouble and not the same issue.

@tadatuta Did we started making a faq? Should we make some answers about common errors?

**Comment by evilj0e** [comment] 2015-01-09 19:48
@Kaleb, maker can't find it because something went wrong and bem-core hasn't been installed by bower. You can try to run ```bower i``` in bem-core directory. 
That can solve your problem.

**Comment by tadatuta** [comment] 2015-01-10 15:09
@kaleb actually you should just run `npm install` and it'd install `bower` dependencies on [postinstall](https://github.com/bem/project-stub/blob/bem-core/package.json#L35). but make sure there's no any error messages upon npm install process. if there are any — please paste them here, I'll try to help.

**Comment by tadatuta** [comment] 2015-01-10 15:10
@zxqfox We'd better get rid of such errors ;)
Anyway I can't reproduce it myself...

**Comment by evilj0e** [comment] 2015-01-10 15:22
@tadatuta, it's problem with postinstall on Windows, I think. Because I've got also the same problem on that os.

**Comment by tadatuta** [comment] 2015-01-10 15:37
@evilj0e we recommend `git bash` (http://git-scm.com/) as console on Windows. It'd provide everything necessary. But be aware of https://github.com/bem/bem-tools/pull/595 (will be landed into next minor version of `bem-tools`).

**Closed** 2015-02-17 09:02 UTC
